###############################################################################
#    mySQL 8.0 Official, nginx 1.15 Official, php 7.22 Official-Build         #
###############################################################################
version: "3"
services:

    mysql:
      image: mysql:8.0
      networks:
        - nmp-net
      container_name: mysql
      working_dir: /var/lib/mysql
      volumes:
        - ./db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=1432
        - MYSQL_DATABASE=test
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=1432
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      networks:
        - nmp-net
      container_name: web
      working_dir: /var/www/html
      volumes:
          - ./html:/var/www/html
          - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      image: php-alpine:7.2.12-fpm
      networks:
        - nmp-net
      build:
        context: ./conf
        dockerfile: dockerfile-php-72-alpine-pdo
      container_name: php
      working_dir: /var/www/html
      volumes:
        - ./html:/var/www/html
        - ./conf/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        
networks:
  nmp-net:


